---
title: "NOAA Data Set"
author: "Aleksandr Makarov (adm2190)"
date: "26 February 2016"
output: html_document
runtime: shiny
---

## Flood Exploration

The main goal of this exploration research was to search for the patterns in the floods recorded in one of the datasets provided for the project and to understand what kind of information can lead to deeper understanding of the events and conditions that affect floods and their destructive impact on countries and environment.

To get the broader view of the dataset provided in *`GlobalFloodRecords.xlsx`* we explore the geography of the floods recorded in the dataset from the global prospective emphisizing these events according to their relative damage and effect on the local population.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(shiny)
library(shinyGlobe)
library(lubridate)
library(sp)
library(rworldmap)
library(ggplot2)
library(dplyr)

getFloodDataDisplaced <- function() {
    
    load("floods.RData")
    floods <- floods[(floods$displaced > 100), 
                     c("centroid.y", "centroid.x", "displaced")]
    colnames(floods) <- c("Latitude", "Longitude", "Displaced")
    #which max displaced number to select: relative or absolute
    floods$Displaced <- floods$Displaced / max(floods$Displaced, na.rm = TRUE)
    
    return(floods[complete.cases(floods),])
    
}

getFloodDataDamage <- function() {
    
    load("floods.RData")
    floods <- floods[(floods$displaced > 100), 
                     c("centroid.y", "centroid.x", "damage")]
    colnames(floods) <- c("Latitude", "Longitude", "Damage")
    #which max displaced number to select: relative or absolute
    floods$Damage <- floods$Damage / max(floods$Damage, na.rm = TRUE)
    
    return(floods[complete.cases(floods),])
    
}

coords2country = function(points) {  
    countriesSP <- getMap(resolution='low')

    # convert our list of points to a SpatialPoints object

    #setting CRS directly to that from rworldmap
    pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  

    # use 'over' to get indices of the Polygons object containing each point 
    indices = over(pointsSP, countriesSP)

    return(data.frame(country = indices$ADMIN,    #return the ADMIN names of each country
                continent = indices$REGION,        # returns the continent (7 continents)
                stringsAsFactors = F))
}

getDataByCountry <- function() {
    
    load("floods.RData")
    countries <- coords2country(
                    floods[!(is.na(floods[,c("centroid.x")]) | is.na(floods[,c("centroid.y")])),
                           c("centroid.x", "centroid.y")])
    floods <- cbind(countries,
                    floods[!(is.na(floods[,c("centroid.x")]) | is.na(floods[,c("centroid.y")])),
                           c(8:13, 15:17)])
    
    return(floods[complete.cases(floods),])
    
}

server1 <- function(input, output, session) {
    
    output$globe <- renderGlobe({
        getFloodDataDisplaced()
    })
    
    output$plot <- renderPlot({
        #obtaining and summarizing data
        floods_countries <- getDataByCountry()
        displacedSummary <- floods_countries %>% 
                                group_by(country) %>% 
                                summarise(total = round(sum(displaced) / 10^6, 2))
        df <- head(displacedSummary[order(-displacedSummary$total),], 6)
        df$country <- factor(df$country)
        df <- within(df, 
                     country <- factor(country,
                                       levels=df$country[order(df$total)]))
        #building the plot
        ggp <- ggplot(df, aes(x = country, y = total, fill = country))
        print(ggp + 
                  geom_bar(stat = "identity") +
                  geom_text(aes(x = country, y = total, 
                                label = total, fontface = "bold"),
                            inherit.aes=FALSE, size = 2.7, hjust = 1.2) + 
                  coord_flip() +
                  #scale_colour_brewer() +
                  scale_y_continuous(breaks = c(0,25,50,75,100)) + 
                  ylab("Total Displaced,\nin millions") +
                  theme(
                        legend.position = "none",
                        panel.grid.minor = element_blank(), 
                        panel.grid.major = element_blank(),
                        panel.background = element_blank(),
                        plot.background = element_blank(),
                        axis.title.y = element_blank(),
                        axis.text.y  = element_text(face="bold",angle=30, vjust=0.5, size=6),
                        axis.text.x  = element_text(size=7)
                        )
              )
    }, bg="transparent")
}

server2 <- function(input, output, session) {
    
    output$globe <- renderGlobe({
        getFloodDataDamage()
    })
    
    output$plot <- renderPlot({
        #obtaining and summarizing data
        floods_countries <- getDataByCountry()
        displacedSummary <- floods_countries %>% 
                                group_by(country) %>% 
                                summarise(total = round(sum(damage) / 10^9, 2))
        
        displacedSummary$country <- as.character(displacedSummary$country)
        displacedSummary$country[displacedSummary$country == "United States of America"] <- "USA"
        displacedSummary$country[displacedSummary$country == "United Kingdom"] <- "UK"
        displacedSummary$country <- factor(displacedSummary$country)
        
        df <- head(displacedSummary[order(-displacedSummary$total),], 6)
        df$country <- factor(df$country)
        df <- within(df, 
                     country <- factor(country,
                                       levels=df$country[order(df$total)]))
        #building the plot
        ggp <- ggplot(df, aes(x = country, y = total, fill = country))
        print(ggp + 
                  geom_bar(stat = "identity") +
                  geom_text(aes(x = country, y = ifelse(total > 60, total, total + 45),
                                label = total, fontface = "bold"),
                            inherit.aes=FALSE, size = 2.7, hjust = 1.2) + 
                  coord_flip() +
                  #scale_colour_brewer() +
                  ylab("Total Damage,\nin billion USD") +
                  #scale_y_continuous(limits = c()) + 
                  theme(
                        legend.position = "none",
                        panel.grid.minor = element_blank(), 
                        panel.grid.major = element_blank(),
                        panel.background = element_blank(),
                        plot.background = element_blank(),
                        axis.title.y = element_blank(),
                        axis.text.y  = element_text(angle=30, vjust=0.5, size=6),
                        axis.text.x  = element_text(size=6)
                        )
              )
    }, bg="transparent")
}

ui1 <- shinyUI(
    tagList(
        globeOutput("globe"),
        absolutePanel(id = "controls", class = "panel panel-default", 
                    fixed = TRUE,
                    draggable = TRUE, top = "auto", left = 10, right = "auto", bottom = 10, 
                    width = 250, height = "auto", 
                    h4("The Number of Displaced People"),
                    wellPanel(
                        style = "background-color: #ffffff; border-radius: 10px",
                        plotOutput("plot", width = 250, height = 150)
                        ),
                    style = "opacity: 0.82"
                    )
    )  
)

ui2 <- shinyUI(
    tagList(
        globeOutput("globe"),
        absolutePanel(id = "controls", class = "panel panel-default", 
                    fixed = TRUE,
                    draggable = TRUE, top = "auto", left = 10, right = "auto", bottom = 10,
                    width = 250, height = "auto",
                    h4("The Value of Property Damage"),
                    wellPanel(
                        style = "background-color: #ffffff; border-radius: 10px",
                        plotOutput("plot", width = 250, height = 150)
                        ),
                    style = "opacity: 0.82"
                    ),
        div(id="info", tagList(
            HTML(
                'Made with webGL & shinyGlobe'
            )
        ))
    )  
)

shinyApp(
  ui = ui1, server = server1,
  options=list(
    width="50%", height=450
  )
)

shinyApp(
  ui = ui2, server = server2,
  options=list(
    width="50%", height=450
  )
)
```

As we can see on these visuals, Eastern Asian countries demonstrate the highest rate of people displaced due to the repercussions of the floods in that region as well as a serious damage profile measured in dollars. One of the reasons supporting such observation might be the fact that India and China along with Indonesia and Malaysia are indeed the biggest countries in the world in terms of both absolute number and density of population, and historically the vast amount of people settle down and live next to the sea shores and rivers. All this historical and social development leads to the higher number of people affected by the floods events in these regions, which can be easily inherited from the above charts. What is more, according to the [***Seismic Monitor***](http://ds.iris.edu/seismon/) South Eastern Asian region demonstrates the highest seismic profile surrounded by Indian and Pacific Ocean, which leads to higher frequency of floods and flood-related events, that affect local population.

Another important observation that can be made from these visuals points the attention to the fact that the highest registered damage profile does not quite follow the affected population profile. Still the highest property damage events are registered in coastal and mainland China provinces of Fujian, Zhejiang, Minqing and others along with Sichuan, Hunan, Hubei and others. However, the other major events occured in European countries *(Austria, Romania, UK)* and North and Central America regions *(United States, Mexico, Cuba)*. This might lead us to the hypothesis that the property damage is higher in the European and American countries due to the higher cost of infrastructure in these countries as well as more expensive currency *(all the recorded damage is ranked according to its relative USD value)*. However, this to be said that not every flood event registered in the dataset has a representative record of the property damage profile, as in the most cases it is extremely difficult to obtain such statistics, thus this conclusion cannot be considered as fully representative.


